server:
  port: ${DEMO1_SERVICE_PORT:8081}
spring:
  application:
    name: demo1-service
  datasource:
    url: ${DEMO1_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:100.75.215.139}:${DB_PORT:5432}/${DEMO1_DB_NAME:demo1_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ROCKETMAN123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    properties:
      ssl: true
      sslmode: require
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
eureka:
  instance:
    prefer-ip-address: true
    hostname: demo1-service
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://${EUREKA_SERVER_HOST:eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka/}
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5 