services:
  eureka-server:
    image: eureka-server:latest
    build: 
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "${EUREKA_SERVER_PORT:-8761}:${EUREKA_SERVER_PORT:-8761}"
    environment:
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT:-8761}
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST:-eureka-server}
    networks:
      - spring-net

  demo1-service:
    image: demo1-service:latest
    build: 
      context: ./demo1
      dockerfile: Dockerfile
    ports:
      - "${DEMO1_SERVICE_PORT:-8081}:${DEMO1_SERVICE_PORT:-8081}"
    volumes:
      - demo1_logs:/app/logs
    environment:
      # Render Database Configuration
      - DB_HOST=${DB_HOST:-100.75.215.139}
      - DB_PORT=${DB_PORT:-5432}
      - DEMO1_DB_NAME=${DEMO1_DB_NAME:-demo1_db}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-ROCKETMAN123}
      - DEMO1_DATASOURCE_URL=${DEMO1_DATASOURCE_URL:-jdbc:postgresql://${DB_HOST:-100.75.215.139}:${DB_PORT:-5432}/${DEMO1_DB_NAME:-demo1_db}}
      
      # Supabase Database Configuration
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST:-aws-0-ap-south-1.pooler.supabase.com}
      - SUPABASE_DB_PORT=${SUPABASE_DB_PORT:-5432}
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME:-postgres}
      - SUPABASE_DB_USERNAME=${SUPABASE_DB_USERNAME:-postgres.yseolfesfpymybqrgmpn}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD:-Rocketman@123}
      - DEMO1_SUPABASE_DATASOURCE_URL=${DEMO1_SUPABASE_DATASOURCE_URL:-jdbc:postgresql://${SUPABASE_DB_HOST:-aws-0-ap-south-1.pooler.supabase.com}:${SUPABASE_DB_PORT:-5432}/${SUPABASE_DB_NAME:-postgres}}
      
      # JPA Configuration
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM:-org.hibernate.dialect.PostgreSQLDialect}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO:-none}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL:-true}
      
      # Eureka Configuration
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST:-eureka-server}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT:-8761}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://${EUREKA_SERVER_HOST:-eureka-server}:${EUREKA_SERVER_PORT:-8761}/eureka/}
      
      # Service Configuration
      - DEMO1_SERVICE_PORT=${DEMO1_SERVICE_PORT:-8081}
    networks:
      - spring-net
    depends_on:
      - eureka-server

  demo2-service:
    image: demo2-service:latest
    build: 
      context: ./demo2
      dockerfile: Dockerfile
    ports:
      - "${DEMO2_SERVICE_PORT:-8082}:${DEMO2_SERVICE_PORT:-8082}"
    volumes:
      - demo2_logs:/app/logs
    environment:
      # Render Database Configuration
      - DB_HOST=${DB_HOST:-100.75.215.139}
      - DB_PORT=${DB_PORT:-5432}
      - DEMO2_DB_NAME=${DEMO2_DB_NAME:-demo2_db}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-ROCKETMAN123}
      - DEMO2_DATASOURCE_URL=${DEMO2_DATASOURCE_URL:-jdbc:postgresql://${DB_HOST:-100.75.215.139}:${DB_PORT:-5432}/${DEMO2_DB_NAME:-demo2_db}}
      
      # Supabase Database Configuration
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST:-aws-0-ap-south-1.pooler.supabase.com}
      - SUPABASE_DB_PORT=${SUPABASE_DB_PORT:-5432}
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME:-postgres}
      - SUPABASE_DB_USERNAME=${SUPABASE_DB_USERNAME:-postgres.yseolfesfpymybqrgmpn}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD:-Rocketman@123}
      - DEMO2_SUPABASE_DATASOURCE_URL=${DEMO2_SUPABASE_DATASOURCE_URL:-jdbc:postgresql://${SUPABASE_DB_HOST:-aws-0-ap-south-1.pooler.supabase.com}:${SUPABASE_DB_PORT:-5432}/${SUPABASE_DB_NAME:-postgres}}
      
      # JPA Configuration
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM:-org.hibernate.dialect.PostgreSQLDialect}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO:-none}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL:-true}
      
      # Eureka Configuration
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST:-eureka-server}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT:-8761}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://${EUREKA_SERVER_HOST:-eureka-server}:${EUREKA_SERVER_PORT:-8761}/eureka/}
      
      # Service Configuration
      - DEMO2_SERVICE_PORT=${DEMO2_SERVICE_PORT:-8082}
    networks:
      - spring-net
    depends_on:
      - eureka-server

networks:
  spring-net:
    driver: bridge

volumes:
  demo1_logs:
  demo2_logs: