server:
  port: ${EUREKA_SERVER_PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:eureka-server}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 1000
    renewalPercentThreshold: 0.85
    peerEurekaNodesUpdateIntervalMs: 1000 